backend:
  name: github
  repo: Kashank3/4youprinting-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/home/hero.yml"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "text" }
