backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://guiless-frangipane-d77776.netlify.app
display_url: https://guiless-frangipane-d77776.netlify.app

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/hero.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - label: "Slides"
            name: "slides"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "image", widget: "image" }
